# Generated by Django 2.2.9 on 2020-12-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_video', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoInfo',
        ),
    ]
