# Generated by Django 2.2.9 on 2020-12-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('video_id', models.IntegerField()),
                ('video_name', models.TextField()),
                ('video_shot_by', models.CharField(max_length=20)),
                ('video_url', models.TextField()),
                ('video_like_num', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('password', models.TextField()),
            ],
        ),
    ]
