# Generated by Django 2.2.9 on 2020-12-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201204_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
